version: '3.1'

services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: dev
      POSTGRES_DB: farmers_db
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      - dev_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@test.com
      PGADMIN_DEFAULT_PASSWORD: dev
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - dev_network
    ports:
      - "5050:80"

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_db_volume:
    driver: local
  pgadmin_volume:
    driver: local